import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useVenue } from '@/lib/venue-context';
import { useReferralAccess } from '@/hooks/use-referral-access';
import { Card, CardContent } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { TrendingUp, DollarSign, Users, Receipt } from 'lucide-react';

export function RevenueHero() {
  const { currentVenue } = useVenue();
  const { venueHasAccess } = useReferralAccess();

  const { data, isLoading } = useQuery({
    queryKey: ['revenue-hero', currentVenue?.id],
    queryFn: async () => {
      if (!currentVenue) return null;

      const now = new Date();
      const monthStart = new Date(now.getFullYear(), now.getMonth(), 1).toISOString();

      const [revenueRes, referralRes, contentRes] = await Promise.all([
        supabase
          .from('revenue_signals')
          .select('revenue_estimate')
          .eq('venue_id', currentVenue.id)
          .gte('created_at', monthStart),
        venueHasAccess
          ? supabase
              .from('referral_bookings')
              .select('verified_spend, commission_amount')
              .eq('venue_id', currentVenue.id)
              .eq('spend_verified', true)
              .gte('created_at', monthStart)
          : Promise.resolve({ data: [] }),
        supabase
          .from('content_items')
          .select('id', { count: 'exact', head: true })
          .eq('venue_id', currentVenue.id)
          .gte('created_at', monthStart),
      ]);

      const attributedRevenue = (revenueRes.data ?? []).reduce(
        (sum, r) => sum + (Number(r.revenue_estimate) || 0),
        0
      );
      const referralRevenue = (referralRes.data ?? []).reduce(
        (sum, b) => sum + (Number(b.verified_spend) || 0),
        0
      );
      const contentCreated = contentRes.count ?? 0;

      return {
        totalRevenue: attributedRevenue + referralRevenue,
        referralRevenue,
        contentCreated,
      };
    },
    enabled: !!currentVenue,
  });

  if (isLoading) {
    return <Skeleton className="h-32 rounded-xl" />;
  }

  const stats = data ?? { totalRevenue: 0, referralRevenue: 0, contentCreated: 0 };

  return (
    <Card className="bg-gradient-to-br from-accent/15 via-card to-card border-accent/20 overflow-hidden relative">
      <div className="absolute inset-0 bg-gradient-to-r from-accent/5 to-transparent pointer-events-none" />
      <CardContent className="p-6 relative">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div>
            <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider mb-1">
              Revenue Generated by Pulse
            </p>
            <p className="text-4xl font-bold text-foreground tracking-tight">
              £{stats.totalRevenue.toLocaleString('en-GB', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}
            </p>
            <p className="text-xs text-muted-foreground mt-1">This month</p>
          </div>

          <div className="flex gap-6">
            {venueHasAccess && (
              <MetricPill
                icon={Users}
                label="Referral Revenue"
                value={`£${stats.referralRevenue.toLocaleString('en-GB', { minimumFractionDigits: 0 })}`}
              />
            )}
            <MetricPill
              icon={TrendingUp}
              label="Content Created"
              value={String(stats.contentCreated)}
            />
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

function MetricPill({ icon: Icon, label, value }: { icon: any; label: string; value: string }) {
  return (
    <div className="text-right">
      <div className="flex items-center gap-1.5 justify-end mb-0.5">
        <Icon className="w-3.5 h-3.5 text-muted-foreground" />
        <span className="text-[10px] text-muted-foreground uppercase tracking-wider">{label}</span>
      </div>
      <p className="text-lg font-semibold">{value}</p>
    </div>
  );
}
